import {
  AirTravel,
  Arthritis,
  Asthma,
  BikingCycling,
  CommonCold,
  Composting,
  Driving,
  DustDander,
  Fishing,
  Flu,
  Golf,
  Hiking,
  LawnMowing,
  Migraine,
  Mosquitos,
  OutdoorEntertaining,
  Running,
  SinusPressure,
  Stargazing,
} from "../assets/icons";
import {
  Sunny,
  Cloudy,
  DrearyOvercast,
  Flurries,
  Fog,
  HazySunshine,
  InterMittentClouds,
  MostlySunny,
  MostlyCloud,
  MostlyCloudyWFlurries,
  MostlyCloudyWShowers,
  MostlyCloudyWTStorms,
  PartlySunnyWShowers,
  PartlySunnyWTStorms,
  PartlySunny,
  Rain,
  Showers,
  TStorms,
  Clear,
  Cold,
  HazyMoonlight,
  Hot,
  Ice,
  MostlyClear,
  MostlyCloudyWSnow,
  PartlyCloudy,
  PartlyCloudyWTStorms,
  RainAndSnow,
  Sleet,
  Snow,
  Windy,
  Lahore,
  Peshawar,
  Karachi,
  Quetta,
} from "../assets/images";

export const weatherIcons = [
  { name: "Sunny", icon: Sunny },
  { name: "Cloudy", icon: Cloudy },
  { name: "Dreary (Overcast)", icon: DrearyOvercast },
  { name: "Flurries", icon: Flurries },
  { name: "Fog", icon: Fog },
  { name: "Hazy sunshine", icon: HazySunshine },
  { name: "Intermittent clouds", icon: InterMittentClouds },
  { name: "Mostly sunny", icon: MostlySunny },
  { name: "Mostly Cloudy", icon: MostlyCloud },
  { name: "Mostly cloudy w/ Flurries", icon: MostlyCloudyWFlurries },
  { name: "Mostly cloudy w/ Showers", icon: MostlyCloudyWShowers },
  { name: "Mostly cloudy w/ T-Storms", icon: MostlyCloudyWTStorms },
  { name: "Partly sunny w/ showers", icon: PartlySunnyWShowers },
  { name: "Partly sunny w/ T-Storms", icon: PartlySunnyWTStorms },
  { name: "Partly Sunny", icon: PartlySunny },
  { name: "Rain", icon: Rain },
  { name: "Showers", icon: Showers },
  { name: "T-Storms", icon: TStorms },
  { name: "Clear", icon: Clear },
  { name: "Cold", icon: Cold },
  { name: "Hazy moonlight", icon: HazyMoonlight },
  { name: "Hot", icon: Hot },
  { name: "Ice", icon: Ice },
  { name: "Mostly clear", icon: MostlyClear },
  { name: "Mostly cloudy", icon: MostlyCloud },
  { name: "Mostly cloudy w/ Snow", icon: MostlyCloudyWSnow },
  { name: "Partly cloudy", icon: PartlyCloudy },
  { name: "Mostly cloudy w/ Showers", icon: PartlySunnyWShowers },
  { name: "Partly cloudy w/ T-Storms", icon: PartlyCloudyWTStorms },
  { name: "Rain and Snow", icon: RainAndSnow },
  { name: "Sleet", icon: Sleet },
  { name: "Snow", icon: Snow },
  { name: "Windy", icon: Windy },
];

export const healthIcons = [
  { name: "Arthritis Pain Forecast", icon: <Arthritis /> },
  { name: "Flight Delays", icon: <AirTravel /> },
  { name: "Asthma Forecast", icon: <Asthma /> },
  { name: "Bicycling Forecast", icon: <BikingCycling /> },
  { name: "Common Cold Forecast", icon: <CommonCold /> },
  { name: "Composting Forecast", icon: <Composting /> },
  { name: "Driving Travel Index", icon: <Driving /> },
  { name: "Fishing Forecast", icon: <Fishing /> },
  { name: "Flu Forecast", icon: <Flu /> },
  { name: "Golf Weather Forecast", icon: <Golf /> },
  { name: "Lawn Mowing Forecast", icon: <LawnMowing /> },
  { name: "Migraine Headache Forecast", icon: <Migraine /> },
  { name: "Mosquito Activity Forecast", icon: <Mosquitos /> },
  { name: "Outdoor Activity Forecast", icon: <OutdoorEntertaining /> },
  { name: "Indoor Activity Forecast", icon: <OutdoorEntertaining /> },
  { name: "Running Forecast", icon: <Running /> },
  { name: "Jogging Forecast", icon: <Running /> },
  { name: "Sinus Headache Forecast", icon: <SinusPressure /> },
  { name: "Stargazing Forecast", icon: <Stargazing /> },
  { name: "Dust & Dander Forecast", icon: <DustDander /> },
  { name: "Beach & Pool Forecast", icon: <DustDander /> },
  { name: "Hiking Forecast", icon: <Hiking /> },
];

export const qualityList = [
  {
    qualityName: "Air Quality",
    qualityValue: "unhealthy",
  },
  {
    qualityName: "Wind",
    qualityValue: "S 7 km/h",
  },
  {
    qualityName: "Wind Guest",
    qualityValue: "7 km/h",
  },
];

export const navLinks = [
  { name: "Today", routeID: "today" },
  { name: "Hourly", routeID: "hourly" },
  { name: "Daily", routeID: "daily" },
  { name: "Health", routeID: "health" },
];

export const popularCityList = [
  { name: "Lahore", province: "Punjab", img: Lahore, key: "260622" },
  { name: "Peshawar", province: "KPK", img: Peshawar, key: "259370" },
  { name: "Karachi", province: "Sindh", img: Karachi, key: "261158" },
  { name: "Quetta", province: "Baluchistan", img: Quetta, key: "257185" },
];
